export const servicesEs = [
  {
    id: 0,
    title: "Front-End",
    description: `El Front-End es la parte mas esencial de tu sitio web, es el lugar donde el cliente encuentra 
    toda la informacion sobre ti o tu negocio, tiene que ser hermosa, y aqui estoy para ayudarte a hacerlo, con las mejores tecnologias, 
    desde lo basico como HTML, CSS y JS, hasta herramientas avanzadas como React, Angular, Vue, Tailwind, o Bootstrap`,
    img: "./img/webfront.webp",
    category: "Desarrollo Web",
  },
  {
    id: 1,
    title: "Back-End",
    description: `Sin embargo, si quieres crecer tu sitio web, vas a necesitar mas que solo el Front-End, entonces, 
    aqui esta mi segundo servicio, Back-End, te ayudare a construir una rapida, segura y perfecta web-app, 
    usando tecnologias como Node.js, Express.js, PHP, Laravel, MySQL y MongoDB`,
    img: "./img/webback.webp",
    category: "Desarrollo Web",
  },
];

export const servicesEn = [
  {
    id: 0,
    title: "Front-End",
    description: `Front-End is the most essential part of your website, 
    is the place where a client finds all your information about you or your business, 
    It has to be beatiful by the way, so I'm here to help you to do it, with the best technologies, 
    from basics like HTML, CSS and JS, to advanced tools such as React, Angular, Vue, Tailwind or Bootstrap`,
    img: "./img/webfront.webp",
    category: "Web Development",
  },
  {
    id: 1,
    title: "Back-End",
    description: `However, if you want to grow up your website you'll need more than only Front-end, 
    so here is second service, Back-End, I'll help you to build a fast, secure, and perfect web-app, 
    using technologies like Node.js, Express.js, PHP, Laravel, MySQL and MongoDB`,
    img: "./img/webback.webp",
    category: "Web Development",
  },
];

export const projectsEn = [
  {
    id: 0,
    title: "urTaskManager",
    description: `This was my first webapp where users can save their taks, 
    built in SCSS / SASS for client side, PHP and MySQL for server side saving all data of users`,
    img: "./img/urtm.webp",
    category: "Web Development",
    url: "https://urtaskmanager.herokuapp.com/",
    github: "https://github.com/MrJoustinOF/urTaskManager",
  },
  {
    id: 1,
    title: "urDevsTogether",
    description: `This is a simple webapp, built in Laravel and MySQL, 
    you'll find a place where devs can add their projects and contact them`,
    img: "./img/urdt.webp",
    category: "Web Development",
    url: "http://urdevstogether.herokuapp.com/",
    github: "https://github.com/MrJoustinOF/urDevsTogether",
  },
  {
    id: 2,
    title: "urResourcesNetwork",
    description: `The place where everyone can publish every resource they want, this webapp was built in the MERN Stack (MongoDB, Express, React, Node)`,
    img: "./img/urrn.webp",
    category: "Web Development",
    url: "https://urrn.vercel.app/",
    github: "https://github.com/MrJoustinOF/urrn",
  },
  {
    id: 3,
    title: "urToDoList",
    description: `A simple SPA project built in Angular and TailwindCSS, to add a few tasks yo have to do`,
    img: "./img/urtdl.webp",
    category: "Web Development",
    url: "https://ur-to-do-list.vercel.app/",
    github: "https://github.com/MrJoustinOF/ur-ToDo-list",
  },
  {
    id: 4,
    title: "urFavEatery",
    description: `This is a concept of a restaurant web, built in React  and TailwindCSS`,
    img: "./img/urfe.webp",
    category: "Web Development",
    url: "https://urfaveatery.netlify.app/",
    github: "https://github.com/MrJoustinOF/urfaveatery",
  },
  {
    id: 5,
    title: "urFrontStore",
    description: `Concept of a t-shirt's store, built in Vue and SCSS / SASS`,
    img: "./img/urfs.webp",
    category: "Web Development",
    url: "https://ur-front-store.vercel.app/#/",
    github: "https://github.com/MrJoustinOF/ur-front-store",
  },
];

export const projectsEs = [
  {
    id: 0,
    title: "urTaskManager",
    description: `Esta fue mi primera webapp, donde los usuarios pueden guardar sus tareas, 
    hecho en SCSS / SASS para el lado del cliente, PHP y MySQL para la parte del servidor guardando 
    toda la informacion de los usuarios`,
    img: "./img/urtm.webp",
    category: "Desarrollo Web",
    url: "https://urtaskmanager.herokuapp.com/",
    github: "https://github.com/MrJoustinOF/urTaskManager",
  },
  {
    id: 1,
    title: "urDevsTogether",
    description: `Esta es una simple webapp, hecha en Laravel y MySQL, 
    encontraras un lugar donde los devs puedan añadir sus proyectos y contactarlos`,
    img: "./img/urdt.webp",
    category: "Desarrollo Web",
    url: "http://urdevstogether.herokuapp.com/",
    github: "https://github.com/MrJoustinOF/urDevsTogether",
  },
  {
    id: 2,
    title: "urResourcesNetwork",
    description: `El lugar donde todos pueden publicar cada recurso que quieran, esta webapp fue hecha en el stack MERN (MongoDB, Express, React, Node)`,
    img: "./img/urrn.webp",
    category: "Desarrollo Web",
    url: "https://urrn.vercel.app/",
    github: "https://github.com/MrJoustinOF/urrn",
  },
  {
    id: 3,
    title: "urToDoList",
    description: `Un simple proyecto SPA hecho en Angular y TailwindCSS para agregar unas cuentas tareas que tengas que hacer`,
    img: "./img/urtdl.webp",
    category: "Desarrollo Web",
    url: "https://ur-to-do-list.vercel.app/",
    github: "https://github.com/MrJoustinOF/ur-ToDo-list",
  },
  {
    id: 4,
    title: "urFavEatery",
    description: `Este es un concepto de una web de un restaurante, hecho en React y TailwindCSS`,
    img: "./img/urfe.webp",
    category: "Desarrollo Web",
    url: "https://urfaveatery.netlify.app/",
    github: "https://github.com/MrJoustinOF/urfaveatery",
  },
  {
    id: 5,
    title: "urFrontStore",
    description: `Concepto de una tienda de camisetas, hecho en Vue y SCSS / SASS`,
    img: "./img/urfs.webp",
    category: "Desarrollo Web",
    url: "https://ur-front-store.vercel.app/#/",
    github: "https://github.com/MrJoustinOF/ur-front-store",
  },
];
